LABS = [{'DESCRIPTION': 'Glucose', 'UNITS': 'mg/dL'},
{'DESCRIPTION': 'Urea Nitrogen', 'UNITS': 'mg/dL'},
{'DESCRIPTION': 'Creatinine', 'UNITS': 'mg/dL'},
{'DESCRIPTION': 'Calcium', 'UNITS': 'mg/dL'},
{'DESCRIPTION': 'Sodium', 'UNITS': 'mmol/L'},
{'DESCRIPTION': 'Potassium', 'UNITS': 'mmol/L'},
{'DESCRIPTION': 'Chloride', 'UNITS': 'mmol/L'},
{'DESCRIPTION': 'Carbon Dioxide', 'UNITS': 'mmol/L'},
{'DESCRIPTION': 'Total Cholesterol', 'UNITS': 'mg/dL'},
{'DESCRIPTION': 'Triglycerides', 'UNITS': 'mg/dL'},
{'DESCRIPTION': 'Low Density Lipoprotein Cholesterol', 'UNITS': 'mg/dL'},
{'DESCRIPTION': 'High Density Lipoprotein Cholesterol', 'UNITS': 'mg/dL'},
{'DESCRIPTION': 'Hemoglobin A1c/Hemoglobin.total in Blood', 'UNITS': '%'},
{'DESCRIPTION': 'Leukocytes [#/volume] in Blood by Automated count',
'UNITS': '10*3/uL'},
{'DESCRIPTION': 'Erythrocytes [#/volume] in Blood by Automated count',
'UNITS': '10*6/uL'},
{'DESCRIPTION': 'Hemoglobin [Mass/volume] in Blood', 'UNITS': 'g/dL'},
{'DESCRIPTION': 'Hematocrit [Volume Fraction] of Blood by Automated count',
'UNITS': '%'},
{'DESCRIPTION': 'MCV [Entitic volume] by Automated count', 'UNITS': 'fL'},
{'DESCRIPTION': 'MCH [Entitic mass] by Automated count', 'UNITS': 'pg'},
{'DESCRIPTION': 'MCHC [Mass/volume] by Automated count', 'UNITS': 'g/dL'},
{'DESCRIPTION': 'Erythrocyte distribution width [Entitic volume] by Automated count',
'UNITS': 'fL'},
{'DESCRIPTION': 'Platelets [#/volume] in Blood by Automated count',
'UNITS': '10*3/uL'},
{'DESCRIPTION': 'Platelet distribution width [Entitic volume] in Blood by Automated count',
'UNITS': 'fL'},
{'DESCRIPTION': 'Platelet mean volume [Entitic volume] in Blood by Automated count',
'UNITS': 'fL'},
{'DESCRIPTION': 'Glomerular filtration rate/1.73 sq M.predicted',
'UNITS': 'mL/min'},
{'DESCRIPTION': 'Glucose [Mass/volume] in Urine by Test strip',
'UNITS': 'mg/dL'},
{'DESCRIPTION': 'Bilirubin.total [Mass/volume] in Urine by Test strip',
'UNITS': 'mg/dL'},
{'DESCRIPTION': 'Ketones [Mass/volume] in Urine by Test strip',
'UNITS': 'mg/dL'},
{'DESCRIPTION': 'Specific gravity of Urine by Test strip',
'UNITS': '{nominal}'},
{'DESCRIPTION': 'pH of Urine by Test strip', 'UNITS': 'pH'},
{'DESCRIPTION': 'Protein [Mass/volume] in Urine by Test strip',
'UNITS': 'mg/dL'},
{'DESCRIPTION': 'Erythrocyte distribution width [Ratio] by Automated count',
'UNITS': '%'},
{'DESCRIPTION': 'Neutrophils/100 leukocytes in Blood by Automated count',
'UNITS': '%'},
{'DESCRIPTION': 'Lymphocytes/100 leukocytes in Blood by Automated count',
'UNITS': '%'},
{'DESCRIPTION': 'Monocytes/100 leukocytes in Blood by Automated count',
'UNITS': '%'},
{'DESCRIPTION': 'Eosinophils/100 leukocytes in Blood by Automated count',
'UNITS': '%'},
{'DESCRIPTION': 'Basophils/100 leukocytes in Blood by Automated count',
'UNITS': '%'},
{'DESCRIPTION': 'Neutrophils [#/volume] in Blood by Automated count',
'UNITS': '10*3/uL'},
{'DESCRIPTION': 'Lymphocytes [#/volume] in Blood by Automated count',
'UNITS': '10*3/uL'},
{'DESCRIPTION': 'Monocytes [#/volume] in Blood by Automated count',
'UNITS': '10*3/uL'},
{'DESCRIPTION': 'Eosinophils [#/volume] in Blood by Automated count',
'UNITS': '10*3/uL'},
{'DESCRIPTION': 'Basophils [#/volume] in Blood by Automated count',
'UNITS': '10*3/uL'},
{'DESCRIPTION': 'Glucose [Mass/volume] in Serum or Plasma', 'UNITS': 'mg/dL'},
{'DESCRIPTION': 'Urea nitrogen [Mass/volume] in Serum or Plasma',
'UNITS': 'mg/dL'},
{'DESCRIPTION': 'Creatinine [Mass/volume] in Serum or Plasma',
'UNITS': 'mg/dL'},
{'DESCRIPTION': 'Calcium [Mass/volume] in Serum or Plasma', 'UNITS': 'mg/dL'},
{'DESCRIPTION': 'Sodium [Moles/volume] in Serum or Plasma',
'UNITS': 'mmol/L'},
{'DESCRIPTION': 'Potassium [Moles/volume] in Serum or Plasma',
'UNITS': 'mmol/L'},
{'DESCRIPTION': 'Chloride [Moles/volume] in Serum or Plasma',
'UNITS': 'mmol/L'},
{'DESCRIPTION': 'Carbon dioxide  total [Moles/volume] in Serum or Plasma',
'UNITS': 'mmol/L'},
{'DESCRIPTION': 'Protein [Mass/volume] in Serum or Plasma', 'UNITS': 'g/dL'},
{'DESCRIPTION': 'Albumin [Mass/volume] in Serum or Plasma', 'UNITS': 'g/dL'},
{'DESCRIPTION': 'Bilirubin.total [Mass/volume] in Serum or Plasma',
'UNITS': 'mg/dL'},
{'DESCRIPTION': 'Alkaline phosphatase [Enzymatic activity/volume] in Serum or Plasma',
'UNITS': 'U/L'},
{'DESCRIPTION': 'Alanine aminotransferase [Enzymatic activity/volume] in Serum or Plasma',
'UNITS': 'U/L'},
{'DESCRIPTION': 'Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma',
'UNITS': 'U/L'},
{'DESCRIPTION': 'Fibrin D-dimer FEU [Mass/volume] in Platelet poor plasma',
'UNITS': 'ug/mL'},
{'DESCRIPTION': 'Ferritin [Mass/volume] in Serum or Plasma', 'UNITS': 'ug/L'},
{'DESCRIPTION': 'Troponin I.cardiac [Mass/volume] in Serum or Plasma by High sensitivity method',
'UNITS': 'pg/mL'},
{'DESCRIPTION': 'Lactate dehydrogenase [Enzymatic activity/volume] in Serum or Plasma by Lactate to pyruvate reaction',
'UNITS': 'U/L'},
{'DESCRIPTION': 'Creatine kinase [Enzymatic activity/volume] in Serum or Plasma',
'UNITS': 'U/L'},
{'DESCRIPTION': 'C reactive protein [Mass/volume] in Serum or Plasma',
'UNITS': 'mg/L'},
{'DESCRIPTION': 'Prothrombin time (PT)', 'UNITS': 's'},
{'DESCRIPTION': 'INR in Platelet poor plasma by Coagulation assay',
'UNITS': '{INR}'},
{'DESCRIPTION': 'Procalcitonin [Mass/volume] in Serum or Plasma',
'UNITS': 'ng/mL'},
{'DESCRIPTION': 'NT-proBNP', 'UNITS': 'pg/mL'},
{'DESCRIPTION': 'Magnesium [Mass/volume] in Serum or Plasma',
'UNITS': 'mg/dL'},
{'DESCRIPTION': 'Iron [Mass/volume] in Serum or Plasma', 'UNITS': 'ug/dL'},
{'DESCRIPTION': 'Iron binding capacity [Mass/volume] in Serum or Plasma',
'UNITS': 'ug/dL'},
{'DESCRIPTION': 'Iron saturation [Mass Fraction] in Serum or Plasma',
'UNITS': '%'},
{'DESCRIPTION': 'Left ventricular Ejection fraction', 'UNITS': '%'},
{'DESCRIPTION': 'Hematocrit [Volume Fraction] of Blood', 'UNITS': '%'},
{'DESCRIPTION': 'WBC Auto (Bld) [#/Vol]', 'UNITS': '10*3/uL'},
{'DESCRIPTION': 'RBC Auto (Bld) [#/Vol]', 'UNITS': '10*6/uL'},
{'DESCRIPTION': 'RDW - Erythrocyte distribution width Auto (RBC) [Entitic vol]',
'UNITS': 'fL'},
{'DESCRIPTION': 'Globulin [Mass/volume] in Serum by calculation',
'UNITS': 'g/L'},
{'DESCRIPTION': 'Hemoglobin.gastrointestinal [Presence] in Stool by Immunologic method',
'UNITS': 'ng/mL'},
{'DESCRIPTION': 'Microalbumin Creatinine Ratio', 'UNITS': 'mg/g'},
{'DESCRIPTION': 'Estimated Glomerular Filtration Rate',
'UNITS': 'mL/min/{1.73_m2}'},
{'DESCRIPTION': 'Peanut IgE Ab in Serum', 'UNITS': 'kU/L'},
{'DESCRIPTION': 'Walnut IgE Ab in Serum', 'UNITS': 'kU/L'},
{'DESCRIPTION': 'Codfish IgE Ab in Serum', 'UNITS': 'kU/L'},
{'DESCRIPTION': 'Shrimp IgE Ab in Serum', 'UNITS': 'kU/L'},
{'DESCRIPTION': 'Wheat IgE Ab in Serum', 'UNITS': 'kU/L'},
{'DESCRIPTION': 'Egg white IgE Ab in Serum', 'UNITS': 'kU/L'},
{'DESCRIPTION': 'Soybean IgE Ab in Serum', 'UNITS': 'kU/L'},
{'DESCRIPTION': 'Cow milk IgE Ab in Serum', 'UNITS': 'kU/L'},
{'DESCRIPTION': 'White oak IgE Ab in Serum', 'UNITS': 'kU/L'},
{'DESCRIPTION': 'Common Ragweed IgE Ab in Serum', 'UNITS': 'kU/L'},
{'DESCRIPTION': 'Cat dander IgE Ab in Serum', 'UNITS': 'kU/L'},
{'DESCRIPTION': 'American house dust mite IgE Ab in Serum', 'UNITS': 'kU/L'},
{'DESCRIPTION': 'Cladosporium herbarum IgE Ab in Serum', 'UNITS': 'kU/L'},
{'DESCRIPTION': 'Honey bee IgE Ab in Serum', 'UNITS': 'kU/L'},
{'DESCRIPTION': 'Latex IgE Ab in Serum', 'UNITS': 'kU/L'},
{'DESCRIPTION': 'Lactate [Moles/volume] in Blood', 'UNITS': 'mmol/L'},
{'DESCRIPTION': 'Diastolic Blood Pressure', 'UNITS': 'mm[Hg]'},
{'DESCRIPTION': 'Magnesium [Mass/volume] in Blood', 'UNITS': 'mg/dL'},
{'DESCRIPTION': 'aPTT in Blood by Coagulation assay', 'UNITS': 's'},
{'DESCRIPTION': 'Troponin I.cardiac [Mass/volume] in Serum or Plasma by High sensitivity method',
'UNITS': 'ng/L'},
{'DESCRIPTION': 'Phosphate [Mass/volume] in Serum or Plasma',
'UNITS': 'mg/dL'},
{'DESCRIPTION': 'pH of Arterial blood', 'UNITS': '[pH]'},
{'DESCRIPTION': 'Carbon dioxide [Partial pressure] in Arterial blood',
'UNITS': 'mm[Hg]'},
{'DESCRIPTION': 'Oxygen [Partial pressure] in Arterial blood',
'UNITS': 'mm[Hg]'},
{'DESCRIPTION': 'Bicarbonate [Moles/volume] in Arterial blood',
'UNITS': 'mmol/L'},
{'DESCRIPTION': 'Activated clotting time (ACT) of Blood by Coagulation assay',
'UNITS': 's'},
{'DESCRIPTION': 'pH of Venous blood', 'UNITS': '[pH]'},
{'DESCRIPTION': 'Carbon dioxide [Partial pressure] in Venous blood',
'UNITS': 'mm[Hg]'},
{'DESCRIPTION': 'Oxygen [Partial pressure] in Venous blood',
'UNITS': 'mm[Hg]'},
{'DESCRIPTION': 'Bicarbonate [Moles/volume] in Venous blood',
'UNITS': 'mmol/L'},
{'DESCRIPTION': 'Carbon dioxide  total [Moles/volume] in Venous blood',
'UNITS': 'mmol/L'},
{'DESCRIPTION': 'Thyrotropin [Units/volume] in Serum or Plasma',
'UNITS': 'm[IU]/L'}]

 
    
VITALS = [{'DESCRIPTION': 'Body Height', 'UNITS': 'cm'},
 {'DESCRIPTION': 'Pain severity - 0-10 verbal numeric rating [Score] - Reported',
  'UNITS': '{score}'},
 {'DESCRIPTION': 'Body Weight', 'UNITS': 'kg'},
 {'DESCRIPTION': 'Body Mass Index', 'UNITS': 'kg/m2'},
 {'DESCRIPTION': 'Body mass index (BMI) [Percentile] Per age and gender',
  'UNITS': '%'},
 {'DESCRIPTION': 'Diastolic Blood Pressure', 'UNITS': 'mm[Hg]'},
 {'DESCRIPTION': 'Systolic Blood Pressure', 'UNITS': 'mm[Hg]'},
 {'DESCRIPTION': 'Heart rate', 'UNITS': '/min'},
 {'DESCRIPTION': 'Respiratory rate', 'UNITS': '/min'},
 {'DESCRIPTION': 'Body temperature', 'UNITS': 'Cel'},
 {'DESCRIPTION': 'Oxygen saturation in Arterial blood', 'UNITS': '%'},
 {'DESCRIPTION': 'Weight-for-length Per age and sex', 'UNITS': '%'},
 {'DESCRIPTION': 'Head Occipital-frontal circumference Percentile',
  'UNITS': '%'},
 {'DESCRIPTION': 'Head Occipital-frontal circumference', 'UNITS': 'cm'},
 {'DESCRIPTION': 'Body Temperature', 'UNITS': '[degF]'},
 {'DESCRIPTION': 'Oxygen Saturation', 'UNITS': '%'},
 {'DESCRIPTION': 'Mean blood pressure', 'UNITS': 'mm[Hg]'},
 {'DESCRIPTION': 'Natriuretic peptide.B prohormone N-Terminal [Mass/volume] in Blood by Immunoassay',
  'UNITS': 'pg/mL'}]
